package edts.base.android.core_domain.model

data class RegistrantData (
    val id: Long,
    val name: String,
    val phone: String,
    val branchId: Int?,
    val stockPointId: Int?,
    val stockPointName: String?,
    val address: String,
    val latitude: Double,
    val longitude: Double,
    val oilAmountCommitment: Double,
    val priceCommitment: Double,
    val bankAccount: String?,
    val bankName: String?,
    val pickupDay: Int,
    val pickupTime: Int,
    val outletCode: String?,
    val pickupLatitude: Double,
    val pickupLongitude: Double,
    val pickupAddress: String?,
    val outletName: String?,
    val ktpPict: String?,
    val selfieKtpPict: String?,
    val nik: String?,
    val offeredPriceCommitment: Double?,
    val rejectReason: List<Int>?,
    val branchName: String?,
    val userId: String?,
)